name: KCN Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Pytest Suite
      run: |
        pytest -v

    - name: Build Docker Container
      run: |
        docker build -t kcn-os .
